apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sysfoo
  name: sysfoo
spec:
  ports:
  - name: "8080"
    nodePort: 30100
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: sysfoo
  type: NodePort
status:
  loadBalancer: {}
